<Project>
  <PropertyGroup>
    <!-- Centralizar versiones de paquetes usados en la solución -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.CodeDom" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageVersion Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.14.40608" />
    <PackageVersion Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.14.40608" />
    <PackageVersion Include="AngleSharp" Version="1.4.0" />
    <PackageVersion Include="Topelab.Core.Adapters" Version="1.12.8" />
  </ItemGroup>
</Project>