---
config:
  theme: neo-dark
  layout: elk
---
flowchart LR
    Proyecto7 --> Proyecto4
    Proyecto7 --> Proyecto5
    Proyecto5 --> Proyecto3
    Proyecto5 --> Proyecto2
    Proyecto4 --> Proyecto1
    Proyecto4 --> Proyecto2
    Proyecto4 --> Proyecto3
    Proyecto3 --> Proyecto1
    Proyecto3 --> Proyecto2
    Proyecto2 --> Proyecto1
