---
config:
  theme: neo-dark
  layout: elk
---
flowchart LR
    Proyecto1 --> Proyecto2
    Proyecto1 --> Proyecto3
    Proyecto1 --> Proyecto4
    Proyecto2 --> Proyecto5
    Proyecto2 --> Proyecto3
    Proyecto2 --> Proyecto4
    Proyecto3 --> Proyecto4
    Proyecto3 --> Proyecto5
    Proyecto4 --> Proyecto7
    Proyecto4 --> Proyecto8
    Proyecto4 --> Proyecto9
    Proyecto5 --> Proyecto6
    Proyecto5 --> Proyecto7
