// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectRelations
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProjectRelations.53758a59-1e79-4267-9cf7-cae21cd55f0d";
        public const string Name = "ProjectRelations";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Juan López López";
        public const string Tags = "";
    }
}
