<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.1.23</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Views\RelationsUserControl.xaml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Views\RelationsUserControl.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core.Resolver\src\Topelab.Core.Resolver.Microsoft\Topelab.Core.Resolver.Microsoft.csproj" />
    <ProjectReference Include="..\CreateRelationsDiagram\CreateRelationsDiagram.csproj" />
  </ItemGroup>
</Project>