<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>$(SolutionName).$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Version>$(ToolsVersion)</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core.Resolver\src\Topelab.Core.Resolver.Microsoft\Topelab.Core.Resolver.Microsoft.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
  </ItemGroup>
</Project>